apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.ns }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.pkg.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.pkg.name }}
      - name: {{ .Values.app.ns }}-{{ .Values.pkg.name }}
        image: {{ .Values.pkg.name }}:{{ .Values.pkg.ver }}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: {{ .Values.mount.name }}
          mountPath: {{ .Values.mount.path }}
      volumes:
        - name: {{ .Values.mount.name }}
          configMap:
            name: {{ .Values.pkg.name }}-html
