apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.ns }}
spec:
  selector:
    app: {{ .Values.pkg.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.pkg.prt }}
      targetPort: {{ .Values.pkg.tprt }}
